function y = filtro2(x)
%FILTRO2 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 30-May-2018 14:58:17

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR least-squares Lowpass filter designed using the FIRLS function.
    %
    % % All frequency values are in Hz.
    % Fs = 200;  % Sampling Frequency
    %
    % N     = 10;  % Order
    % Fpass = 30;  % Passband Frequency
    % Fstop = 50;  % Stopband Frequency
    % Wpass = 1;   % Passband Weight
    % Wstop = 1;   % Stopband Weight
    %
    % % Calculate the coefficients using the FIRLS function.
    % b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-0.00313418740759487 -0.0507929490517216 ...
        -0.0465423923707065 0.0882749670207434 0.294187669825268 ...
        0.395529677333603 0.294187669825268 0.0882749670207434 ...
        -0.0465423923707065 -0.0507929490517216 -0.00313418740759487]);
end

y = step(Hd,double(x));


% [EOF]
