function y = filtro(x)
%FILTRO Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 30-May-2018 14:38:06

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % Equiripple Lowpass filter designed using the FIRPM function.
    
    % All frequency values are in Hz.
    Fs = 200;  % Sampling Frequency
    
    Fpass = 20;              % Passband Frequency
    Fstop = 50;              % Stopband Frequency
    Dpass = 0.057501127785;  % Passband Ripple
    Dstop = 0.0001;          % Stopband Attenuation
    dens  = 20;              % Density Factor
    
    % Calculate the order from the parameters using FIRPMORD.
    [N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
    
    % Calculate the coefficients using the FIRPM function.
    b  = firpm(N, Fo, Ao, W, {dens});
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-0.00211399511009277 -0.0108312122486459 ...
        -0.0274326449216512 -0.0409559485850947 -0.0265400557511611 ...
        0.0374076914324466 0.143482323325245 0.246499705735604 0.289531693621037 ...
        0.246499705735604 0.143482323325245 0.0374076914324466 ...
        -0.0265400557511611 -0.0409559485850947 -0.0274326449216512 ...
        -0.0108312122486459 -0.00211399511009277]);
end

y = step(Hd,double(x));


% [EOF]
